// export default {
//   NODE_ENV: 'muguang',
//   VUE_APP_CURRENTMODE: 'mg',
//   VUE_APP_BASEURL: 'http://www.imuguang.com',
//   VUE_APP_OSSADDRESS: 'http://imuguang-file.oss-cn-shenzhen.aliyuncs.com',
//   VUE_APP_VIDEO: 'http://imuguang-in.oss-cn-shenzhen.aliyuncs.com',
//   VUE_APP_CDN: 'https://f-bd.imuguang.com',
//   VUE_APP_ENDPOINT: 'http://oss-cn-shenzhen.aliyuncs.com',
//   VUE_APP_BUCKET1: 'imuguang-in',
//   VUE_APP_BUCKET2: 'imuguang-file',
//   VUE_APP_DIR_IMG:'img/',
//   VUE_APP_DIR_VIDEO:'video/input/',
// }
// export default {
//   NODE_ENV: 'muguang',
//   VUE_APP_CURRENTMODE: 'mg',
//   VUE_APP_BASEURL: 'http://test.imuguang.com',
//   VUE_APP_OSSADDRESS: 'http://imuguang-file.oss-cn-shenzhen.aliyuncs.com',
//   VUE_APP_VIDEO: 'http://imuguang-in.oss-cn-shenzhen.aliyuncs.com',
//   VUE_APP_CDN: 'https://f-bd.imuguang.com',
//   VUE_APP_ENDPOINT: 'http://oss-cn-shenzhen.aliyuncs.com',
//   VUE_APP_BUCKET1: 'imuguang-in',
//   VUE_APP_BUCKET2: 'imuguang-file',
//   VUE_APP_DIR_IMG:'img/',
//   VUE_APP_DIR_VIDEO:'video/input/',
// }
export default {
    NODE_ENV:'aiyu',
    VUE_APP_CURRENTMODE:'ay',
    VUE_APP_BASEURL:'http://www.aiyu2019.com',
    VUE_APP_OSSADDRESS:'https://aiyuout.oss-cn-shenzhen.aliyuncs.com',
    VUE_APP_CDN_VIDEO:'https://aiyuin.oss-cn-shenzhen.aliyuncs.com',
    VUE_APP_CDN:'https://aiyuout.oss-cn-shenzhen.aliyuncs.com',
    VUE_APP_ENDPOINT:'https://oss-cn-shenzhen.aliyuncs.com',
    VUE_APP_BUCKET1:'aiyuin',
    VUE_APP_BUCKET2:'aiyuout',
    VUE_APP_DIR_IMG:'img/',
    VUE_APP_DIR_VIDEO:'video/input/',
}
